### PR TITLE
Incorporate existing patches from rancid-discuss mailing list to support...

### PR DESCRIPTION
**Pull request by coyhile**
... git as a backend in addition to cvs and svn

### CODE REVIEW

**Comment by coyhile** [comment]
github claims there's a conflict here? I don't see it.  What's conflicting here?

**Comment by mamash** [comment]
I wouldn't worry about that - we cannot merge any pull requests anyway, because upstream pkgsrc is in CVS.

Is there some reference discussion to this patches? Why not commit to rancid upstream directly?

**Comment by coyhile** [comment]
It seems like this idea has been around since 2007; in fact that's the patch that I forward-ported here:  the most recent discussion I can find is this:

http://comments.gmane.org/gmane.network.rancid/7358

which seems to me to indicate that the rancid community  is in favor of this, but the maintainers haven't or wont' support it officially.

Is it perhaps better to create some sort of meta package rancid-git that tracks the net/rancid package and applies the git specific patches?  If that would be preferred, I'd certainly be happy to do that instead.

**Comment by coyhile** [comment]
I'm closing this one, as it appears that rancid folks are working on git support.  I'll use my local package in the interim, then perhaps work on porting the package to, e.g. 3.2 once an update is released with git support.

**Pull request closed without merging**
