### PR TITLE
Workaround for missing local on SmartOS / Solaris. Using typeset instead...

### PR DESCRIPTION
**Pull request by drscream**
To build exim version 4 on SmartOS I using `typeset` on the `scripts/lookups-Makefile`. I'm not 100% sure if `typeset` also exists on BSD and work there as well.

### CODE REVIEW

**Comment by rmustacc** [comment]
Wouldn't the better fix here be to actually invoke bash instead of sh given that the script is clearly using bashisms? The local keyword isn't missing -- it just was never valid syntax in the bourne shell.

**Comment by drscream** [comment]
If using `bash` is okey for all BSD people, i'm also fine with it :-)

**Comment by rmustacc** [comment]
I can't speak for all of them, but typeset is a kshism IIRC and not defined to be available in `/bin`/sh`. But`ksh`just like`bash` basically doesn't care what you invoke it as really and will let you more or less use all the features of the underlying shell which is how you get into a situation like this. That said, I'm not sure what pkgsrc prefers here.

**Comment by jperkin** [comment]
We can make the package depend on bash (add USE_TOOLS= bash:run and REPLACE_BASH any scripts), or sometimes it's just easier to remove any instances of 'local' in shell scripts - it's non portable and very rarely actually useful.  Definitely not typeset, though..

**Comment by drscream** [comment]
Thanks a lot for your idea. I think the best way is to remove the `local` from the script because we could live without it.

**Comment by jperkin** [comment]
I've fixed this in pkgsrc HEAD: http://mail-index.netbsd.org/pkgsrc-changes/2013/09/02/msg094386.html

Will hopefully pull this back to 2013Q2.  Thanks.

**Pull request closed without merging**
