### PR TITLE
add FreeRADIUS 3.x support

### PR DESCRIPTION
**Pull request by coyhile**
Add packages for FreeRADIUS 3.x base server.  Add packages for additional modules that ship the module shared libraries as appropriate similar to what is done in the vendor-provided RHEL spec file.

### CODE REVIEW

**Comment by jperkin** [comment]
Thanks! I'll take a look at this today/tomorrow.

**Comment by coyhile** [comment]
@jperkin One thing I did not do (in the main package) is hack up the manpages.  They contain hard-coded references to `/etc/raddb` which probably should be patched to mention `${PKGSYSCONFBASE}/raddb` (Is that `${PKGSYSCONFDIR}` in this case?)  If that's something that we should do (and there's a reasonable way to do it, I"ll push another commit to the branch..

**Comment by mamash** [comment]
Hi coyhile, I had a look at the package over the weekend. There is some work left, e.g. config files must not install directly into $PKG_SYSCONFDIR. You should have them install to $PREFIX/share/examples/freeradius and then handle via $CONF_FILES, as in the original net/freedius package.

If you are done with the changes, I can wrap that up, because I have some other modifications to e.g. build on NetBSD.

**Comment by coyhile** [comment]
@mamash, I think I've done everything I know how to do. (I don't get the whole `$CONF_FILES` thing, so if you wanted to handle that, I'll try to learn something so that my next contribution requires less massaging.)  Let me see if I can clean up the conf files stuff this evening.

**Comment by coyhile** [comment]
I'm working on making this work correctly with `$CONF_FILES`. I should have another commit that handles that maybe in another day or so.

**Comment by coyhile** [comment]
@jperkin @mamash In my own tests, this now supports CONF_FILES the way I expect it to.

**Comment by mamash** [comment]
Thanks, I'm thinking that having all of mods-available and sites-available inside $PKG_SYSCONFDIR is an overkill, and mostly coming from the fact that traditional distributions do not have a clear separation logic between 'example' and 'live' config files (like pkgsrc does). Note that once you add something to $CONF_FILES, pkgsrc will be 'watching' that file and only overwrite it again from share/examples when the hash sum is unchanged.

I'm thinking it should be enough to leave those under share/examples/freeradius and let the end operator copy or symlink over into $PKG_SYSCONFDIR/{mods-enabled,sites-enabled} as suggested by the docs.

I'm going to test the package(s) now on SmartOS and NetBSD and unless you come up with a strong argument, do just that.

**Comment by coyhile** [comment]
That sounds good to me. The reason I did what I did was to make this setup similar to what upstream does on other distributions.  Your point is valid, though, and I think actually quite a good idea.

**Comment by coyhile** [comment]
@mamash We should, however, leave the symlinks that I drop in mods-enabled / sites-enabled dropped in place so that a default radiusd will start, I would argue.

**Comment by mamash** [comment]
Yes, I see, it's a little bit more complicated. As somehow who most likely uses or has used FreeRadius, how likely are you to have to change the default mods/sites available files?

The config file structure here is highly similar to the one that Apache httpd uses, and which pkgsrc completely does away with, because the symlinks go against the model that pkgsrc uses (i.e. copies made of default example files that are automatically managed by pkgsrc until the first modification you do that breaks the file hash).

**Comment by coyhile** [comment]
It's a toss-up. Personally, I would probably drop files directly in `${PKG_SYSCONFDIR}/mods-enabled` and `${PKG_SYSCONFIDR}/site-enabled` because once I got something working, it'd be handled by chef.  My impression from the mailing lists is that may people just edit the target of the symlink in place and let the symlinks enable something.

I _really_ am not a fan of that paradigm personally.  I'm open to suggestions about the best way to handle it. I just tried to stay as close to what upstream builds do as I could.

**Comment by coyhile** [comment]
@mamash please let me know if there's anything specific you need to do to make this build on NetBSD, as my only experience around pkgsrc is on SmartOS and OSX. That way I can handle it the next time I need to import something.

**Comment by coyhile** [comment]
@mamash A 3.0.14 just got released today.  As this is still open, shall I `bmake distinfo` with 3.0.14 once the tarballs show up?

**Comment by mamash** [comment]
No, too many local changes were needed here, so I'll just adjust for 3.0.14 (and we can't merge PRs). Getting close.

**Comment by coyhile** [comment]
I'd be interested to see how much difference there is so I can learn something.

**Comment by coyhile** [comment]
@mamash did you make much more progress here? i'm interested to see what further massaging is necessary so I can save you guys the work next time.

**Comment by mamash** [comment]
Committed upstream.

**Pull request closed without merging**
