### PR TITLE
Split the cyrus sasl gssapi plugin into two separate packages.

### PR DESCRIPTION
**Pull request by coyhile**
This change brings pkgsrc inline with what other distributions such as Debian do with the GSSAPI plugin.  While the existing cy2-gssapi package can link against the correct GSSAPI implementation (depending upon what is installed on the build box), it does little to help users of binary packages.  Therefore, we split the package into cy2-gssapi-(mit|heimdal) so that users can install a build that has correct Kerberos implementation linked in.

### CODE REVIEW

**Comment by jperkin** [comment]
I'm not sure this will work as-is.  Each package would need to explicitly state which KRB5_TYPE to use, so that the correct dependency is pulled in.

At the very least set KRB5_ACCEPTED in each package Makefile, but I'm not sure how that will behave when KRB5_DEFAULT is not in the list of KRB5_ACCEPTED.  See mk/krb5.buildlink.mk for more details, and have a play to ensure that it works as expected for both packages.

**Comment by coyhile** [comment]
I think explicitly stating --with-gss_impl=mit or --with-gss_impl=heimdal makes it build against the right version.  But I see what you mean about the dependencies (as I don't see either heimdal or mit in the dependencies when I do pkg_info on the local package tarball) I only see

Requires:
{gcc47,gcc47-libs} >=4.7.3
{gcc47,gcc47-libs} >=4.7.0
cyrus-sasl>= 2.1.26
openssl >=1.0.1c

What I don't quite understand is what's different between these packages and the original cy2-gssapi pkg from which I sourced them.

**Comment by coyhile** [comment]
I've made use of Heimdal explicit in the Heimdal-specific package and added conflicts to both packages.  Even though the SunOS platform makefile sets the default Kerberos implementation to MIT, I set the same in my two packages.  Please let me know if that works better; the Heimdal package is in use in production on my KDCs and LDAP servers now.

**Comment by coyhile** [comment]
I've made use of Heimdal explicit in the Heimdal-specific package and added conflicts to both packages.  Even though the SunOS platform makefile sets the default Kerberos implementation to MIT, I set the same in my two packages.  Please let me know if that works better; the Heimdal package is in use in production on my KDCs and LDAP servers now.

**Comment by coyhile** [comment]
@jperkin  this is my first foray into fun with pkgsrc.  Does the latest round of changes (as written) allay the issues?  I can confirm that when I build this on trunk (rather than on the 201xQy release at which my builder box points), it does pull in the latest heimdal from pkgsrc (which is newer than what's installed) as I would expect.

**Comment by coyhile** [comment]
Closing, this is ancient. If it's still needed, I probably should respin this.

**Pull request closed without merging**
