### PR TITLE
Add SMF support for openldap/server

### PR DESCRIPTION
**Pull request by coyhile**
This branch adds SMF support for OpenDLAP server.

### CODE REVIEW

**Comment by coyhile** [comment]
@jperkin @alainodea, please review this one.

**Comment by AlainODea** [comment]
Looks good. Do you need to explictly depend on local-filesystem to depend on a specific file or is that implied?

**Comment by jperkin** [comment]
This is a little trickier than at first glance. The problem is that a number of packages share the common `databases/openldap` directory, and by putting a manifest there it will be picked up by all of them and not only the server.

This will need some extra additions to the `openldap-server` Makefile using variables from `mk/smf.mk` to instruct it where to pick the manifest from. If you want to have a go at this that would be great, otherwise I will get to this when I have some time.

**Comment by coyhile** [comment]
Thanks, Jon. I'll try to take a stab when I have a cycle or three.

**Comment by coyhile** [comment]
@jperkin I've updated this changeset to move the SMF bits into openldap-server where it should have been in the first place.  Please review the latest stab here.

**Pull request closed without merging**
