### PR TITLE
update ap-auth-kerb to build for apache 2.4

### PR DESCRIPTION
**Pull request by nshalman**
The patches from the Fedora project appear to fix the build.
http://pkgs.fedoraproject.org/cgit/mod_auth_kerb.git/tree/

The spec file applies them in this order:
Patch1: mod_auth_kerb-5.4-rcopshack.patch
Patch2: mod_auth_kerb-5.4-fixes.patch
Patch3: mod_auth_kerb-5.4-s4u2proxy.patch
Patch4: mod_auth_kerb-5.4-httpd24.patch
Patch5: mod_auth_kerb-5.4-delegation.patch
Patch6: mod_auth_kerb-5.4-cachedir.patch
Patch7: mod_auth_kerb-5.4-longuser.patch
Patch8: mod_auth_kerb-5.4-handle-continue.patch

I have converted those patches (plus the original
pkgsrc one) into a pair of per-file patches.

### CODE REVIEW

**Comment by nshalman** [comment]
Silly github, this shouldn't be closed yet...

**Comment by mamash** [comment]
Argh, stupid Github. Re-opening again.

**Comment by njones11** [comment]
+1
I'm also being bitten by not having working mod_auth_kerb on SmartOS.

**Comment by nshalman** [comment]
superseded by #213

**Pull request closed without merging**
