### PR TITLE
Fix ncurses when building with GCC 5.1

### PR DESCRIPTION
**Pull request by travispaul**
Fix for building ncurses on Fedora 22 with GCC 5.1, also tested patch against NetBSD with GCC 4.8

### CODE REVIEW

**Comment by jperkin** [comment]
Committed upstream in http://mail-index.netbsd.org/pkgsrc-changes/2015/06/17/msg126164.html and will be in pkgsrc-2015Q2, thanks!

**Comment by travispaul** [comment]
Thanks for committing upstream, I was wondering if I would need to do that as well.

**Comment by travispaul** [comment]
@jperkin Does it make more sense to push non smart-os related patches upstream? Or would you still like those pull requests here as well?

**Comment by jperkin** [comment]
I don't mind non-SmartOS patches here, lots of people are put off by the NetBSD bug system (GNATS) and prefer to just send a pull request, and I'd rather we see the patch and have to handle it ourselves than it never be sent.

However, if people are comfortable sending patches directly upstream then that's preferable, and they'll usually be handled faster (I'm not aware of any non-Joyent pkgsrc developers monitoring this repository, but they will generally see GNATS bugs).

**Pull request closed without merging**
