### PR TITLE
Add SMF support for various Heimdal services

### PR DESCRIPTION
**Pull request by coyhile**
My read of the pkgsrc support means that we have a single manifest.xml, regardless of the number of services, so I have all of the following services in a single service bundle:

kdc -- kerberos key distribution center
kadmin -- kerberos admin service
kpasswdd -- kerberos password change daemon
ipropd  -- two instances (master and slave) for the Heimdal Incremental Propagation Daemon

### CODE REVIEW

**Comment by coyhile** [comment]
@jperkin @alainodea, please review this one.

**Comment by AlainODea** [comment]
Looks sound to me from an SMF perspective. The dependencies look sensible and they are valid manifests otherwise. I'm not familliar with the individual services, Are there dependencies between them that should be made explicit?

**Comment by coyhile** [comment]
On Jun 23, 2014, at 9:05 PM, AlainODea notifications@github.com wrote:

> Looks sound to me from an SMF perspective. The dependencies look sensible and they are valid manifests otherwise. I'm not familliar with the individual services, Are there dependencies between them that should be made explicit?

The only possible dependency is that I cannot imagine running either of the propagation services without the KDC running.  

That said, I could see a use case where someone might have a slave KDC where the KDC itself were, perhaps, not accepting connections, but still wanted to stay up-to-date with database updates as a hot spare of sorts.  

It would make sense that the master iprop service shouldn’t be running unless the KDC is, though, as that service should only run on the master KDC.  However, there’s no requirement that the KDC be up before the propagation master starts. Is there a way to codify, “nobody with any sense would run service B without service A running, but service B shouldn’t refuse to start if A isn’t already running.”

-c

**Comment by AlainODea** [comment]
Interesting challenge :)

The dependency of B on A should be declared with **grouping** set to **optional_all** to reflect "that if the dependency is enabled, it should be started prior to this service, but this service should be brought online regardless of the result of starting the dependency" (OpenSolaris Bible section 13.2.1.2).

**Comment by coyhile** [comment]
On further review, I don't think it's useful to add dependencies like that in there (even if they were grouped as optional_all).  it's entirely possible, especially in heimdal -- potentially less so with MIT -- that a box could be fulfilling different roles for different realms, so all my preconceived notions about how a single-realm setup works go out the window.  I think we should leave the dependencies as is.

**Comment by AlainODea** [comment]
Sounds good.

**Comment by coyhile** [comment]
Do you guys upstream consider this one worthy of merge? I saw @jperkin comments on the openldap pull request need work, and I'll get to that soon.

**Comment by coyhile** [comment]
This is ancient,  closing. I no longer use Heimdal on SmartOS, so I wouldn't be using/testing this further.

**Pull request closed without merging**
