### PR TITLE
Remove syscall.Dup2() support.

### PR DESCRIPTION
**Pull request by sean-**
This is a breaking change, but it is time to rip the bandaid off.
`syscall.Dup2()` will never be merged upstream[1].  Software depending on
`syscall.Dup2()` needs to move to use `unix.Dup2()`.

[1] https://docs.google.com/document/d/1QXzI9I1pOfZPujQzxhyRy6EeHYTQitKKjHfpq0zpxZs/edit
[2] https://godoc.org/golang.org/x/sys/unix#Dup2

### CODE REVIEW

**Comment by jen20** [comment]
I think L89-90 of `Makefile` can also be removed here. Other than that I am strongly supportive of this change to bring us into line with Go compilers on other platforms - and we should patch things which require `Dup2` to use the supported package instead.

**Comment by sean-** [comment]
Good catch, PR updated.

**Review by jen20 — APPROVED** [review]

**Comment by mamash** [comment]
I committed this change to lang/go on trunk now.

**Comment by mamash** [comment]
At least the Go packages that pkgsrc has are fine with this.

**Comment by mamash** [comment]
The updated go-1.8.1nb2 package just landed in 2016Q4, though the mirrors might take an hour or so to synchronize.

**Pull request closed without merging**
