### PR TITLE
Update cfengine3 to 3.7.2

### PR DESCRIPTION
**Pull request by bahamat**
This is the latest stable. I'm hoping to get this in for the upcoming 2015Q4 LTS.

### CODE REVIEW

**Comment by bahamat** [comment]
Cfengine 3.7 itself is an LTS line.

**Comment by mamash** [comment]
I'm working on this now.

**Comment by bahamat** [comment]
Awesome, thanks!

**Comment by mamash** [comment]
Fixing several issues with the update, but one question: where do the SMF manifests come from?

**Comment by bahamat** [comment]
I created them using `manifold`, then modified by hand into their current form.

They've been added to the CfEngine source repository (https://github.com/cfengine/core/tree/master/contrib/solaris-smf), but for some reason are not included in the source code packages.

**Pull request closed without merging**
